# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 23:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragioneSociale', models.CharField(max_length=200, verbose_name='Ragione sociale')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=2000, verbose_name='descrizione')),
                ('oraArrivo', models.CharField(max_length=500, verbose_name='Ora di arrivo')),
                ('note', models.TextField(verbose_name='Note')),
                ('cliente', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Programs.Cliente', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('user_auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telefono', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Cellulare')),
                ('dataDiNascita', models.DateField(blank=True, default=None, null=True, verbose_name='data di nascita')),
            ],
        ),
        migrations.CreateModel(
            name='Amministrativo',
            fields=[
                ('utente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Programs.Utente')),
            ],
            bases=('Programs.utente',),
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('utente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Programs.Utente')),
                ('oreRecupero', models.FloatField(blank=True, default=None, null=True, verbose_name='ore da recuperare')),
                ('lavoroQuota', models.BooleanField(default=True, verbose_name='Lavoro in quota')),
            ],
            bases=('Programs.utente',),
        ),
        migrations.AddField(
            model_name='task',
            name='personaleAssente',
            field=models.ManyToManyField(related_name='assenze', to='Programs.Tecnico', verbose_name='Presonale assente'),
        ),
        migrations.AddField(
            model_name='task',
            name='riferimentoCommessa',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Programs.Amministrativo', verbose_name='Riferimento commessa'),
        ),
        migrations.AddField(
            model_name='task',
            name='tecnici',
            field=models.ManyToManyField(related_name='taskAssegnati', to='Programs.Tecnico', verbose_name='Tecnici'),
        ),
    ]
