# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0002_auto_20171110_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giorno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giorno', models.DateField(verbose_name='Giorno')),
                ('tasks', models.ManyToManyField(to='Programs.Task', verbose_name='Commessa')),
            ],
        ),
    ]
