# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0003_giorno'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='offerta',
            field=models.FileField(null=True, upload_to='', verbose_name='Offerta'),
        ),
    ]
