# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0004_task_offerta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='offerta',
            field=models.FileField(null=True, upload_to='offerte', verbose_name='Offerta'),
        ),
    ]
