# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0005_auto_20171115_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giorno',
            name='tasks',
            field=models.ManyToManyField(null=True, to='Programs.Task', verbose_name='Commessa'),
        ),
    ]
