# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0006_auto_20171115_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giorno',
            name='tasks',
        ),
        migrations.AddField(
            model_name='giorno',
            name='tasks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Programs.Task', verbose_name='Commessa'),
        ),
    ]
