# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0008_auto_20171115_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='giorno',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Programs.Giorno', verbose_name='Data'),
        ),
    ]
