# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0009_auto_20171115_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='giorno',
        ),
        migrations.AddField(
            model_name='task',
            name='giorno',
            field=models.ManyToManyField(default=None, null=True, related_name='attivita', to='Programs.Giorno', verbose_name='Data'),
        ),
    ]
