# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0011_auto_20171115_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='personaleAssente',
        ),
        migrations.AddField(
            model_name='giorno',
            name='personaleAssente',
            field=models.ManyToManyField(blank=True, related_name='assenze', to='Programs.Tecnico', verbose_name='Presonale assente'),
        ),
    ]
