# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0012_auto_20171117_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='note',
            field=models.TextField(null=True, verbose_name='Note'),
        ),
    ]
