# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-19 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0020_auto_20171119_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='oraArrivo',
            field=models.CharField(blank=True, default='--', max_length=500, null=True, verbose_name='Ora di arrivo'),
        ),
    ]
