# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-19 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0022_auto_20171120_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tecnici',
            field=models.ManyToManyField(blank=True, related_name='taskAssegnati', to='Programs.Tecnico', verbose_name='Tecnici'),
        ),
    ]
