# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-19 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0023_auto_20171120_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Programs.Cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='task',
            name='giorno',
            field=models.ManyToManyField(related_name='attivita', to='Programs.Giorno', verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='task',
            name='riferimentoCommessa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Programs.Amministrativo', verbose_name='Riferimento commessa'),
        ),
    ]
